# **Celebal Excellence Internship Data Engineer**
# **Week 1 Assignment**
### **Problem Statement**
**Basic Data Exploration and Cleaning using Pandas**

* **Objective:** Learn Python basics and perform basic data exploration and cleaning tasks using the Pandas library.

### Step-by-Step Instructions

1. **Load the Dataset:** Load a CSV dataset into a Pandas DataFrame.
2. **Explore Data:** `.head()`, `.tail()`, `.shape`, `.columns`, and data types.
3. **Handle Missing Values:** Identify missing entries (`.fillna()`) or dropping (`.dropna()`) them.
4. **Perform Basic Operations:** Filter rows and select columns.
5. **Remove Duplicates:**
6. **Create a new derived column  :**   *total_amount = price * quantity*
7. **Save Cleaned Data:** Export the finalized dataset as a new CSV file.
---
### Resources
* **Dataset Link:** [https://www.kaggle.com/datasets/anvitkumar/shopping-dataset](https://www.kaggle.com/datasets/anvitkumar/shopping-dataset)
---
### Outputs
* Jupyter Notebook (`.ipynb` file)
* Cleaned CSV dataset
* A brief summary report

### **Step 1: Load the Dataset**

In [1]:
import pandas as pd

# 1. Load the CSV dataset into a Pandas DataFrame
file_name = 'Combined_dataset.csv'
df = pd.read_csv(file_name)

print(f'Successfully loaded {file_name}')

Successfully loaded Combined_dataset.csv

### **Step 2: Explore data**

In [2]:
# Display the first 5 rows
print('First 5 rows:')
display(df.head())

First 5 rows:

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [3]:
# Display the last 5 rows
print('\nLast 5 rows:')
display(df.tail())

Last 5 rows:

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [4]:
# Get the shape of the DataFrame (rows, columns)
print(f'\nDataFrame shape: {df.shape}')

DataFrame shape: (1000, 24)

In [5]:
# List all columns and their data types
print('\nColumn information and data types:')
df.info()

Column information and data types:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   object
 2   product_description     1000 non-null   object
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   object
 8   currency                1000 non-null   object
 9   images                  1000 non-null   object
 10  delivery_options        1000 non-null   object
 11  product_details         1000 non-null   object
 12  breadcrumbs             1000 non-null   object
 13  product_specifications  1000 non-null   object
 14  amount_of_stars         1000 non-null   object
 15  what_customers_said     427 non-null    object
 16  seller_name             699 non-null    object
 17  sizes                   1000 non-null   object
 18  videos                  219 non-null    object
 19  seller_information      699 non-null    object
 20  variations              438 non-null    object
 21  best_offer              1000 non-null   object
 22  more_offers             1000 non-null   object
 23  category                1000 non-null   object
dtypes: float64(2), int64(3), object(19)
memory usage: 187.6+ KB

### **Step 3: Handle missing values**

In [6]:
import re

# Identify missing values
print('Missing values before handling:')
display(df.isnull().sum())

Missing values before handling:

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [7]:
# Handle missing values for specific columns
# Fill object columns with 'Unknown'
for col in ['what_customers_said', 'seller_name', 'seller_information', 'variations', 'videos']:
    if col in df.columns:
        df[col] = df[col].fillna('Unknown')

In [8]:
# Fill 'discount' (numeric) with 0 (or mean/median if preferred)
if 'discount' in df.columns:
    df['discount'] = df['discount'].fillna(0)

In [9]:
# Convert 'final_price' to numeric
if 'final_price' in df.columns:
    # Remove all characters that are not digits or a decimal point
    df['final_price'] = df['final_price'].astype(str).str.replace(r'[^\d.]', '', regex=True)
    # Convert to numeric, coercing errors to NaN
    df['final_price'] = pd.to_numeric(df['final_price'], errors='coerce')
    # Fill NaNs with 0 (for any values that couldn't be converted)
    df['final_price'] = df['final_price'].fillna(0)

print('\nMissing values after handling and data type conversions:')
display(df.isnull().sum())
print('\nDataFrame info after handling missing values and converting types:')
df.info()

Missing values after handling and data type conversions:

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

DataFrame info after handling missing values and converting types:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   object
 2   product_description     1000 non-null   object
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                1000 non-null   float64
 7   final_price             1000 non-null   float64
 8   currency                1000 non-null   object
 9   images                  1000 non-null   object
 10  delivery_options        1000 non-null   object
 11  product_details         1000 non-null   object
 12  breadcrumbs             1000 non-null   object
 13  product_specifications  1000 non-null   object
 14  amount_of_stars         1000 non-null   object
 15  what_customers_said     1000 non-null   object
 16  seller_name             1000 non-null   object
 17  sizes                   1000 non-null   object
 18  videos                  1000 non-null   object
 19  seller_information      1000 non-null   object
 20  variations              1000 non-null   object
 21  best_offer              1000 non-null   object
 22  more_offers             1000 non-null   object
 23  category                1000 non-null   object
dtypes: float64(3), int64(3), object(18)
memory usage: 187.6+ KB

### **Step 4: Perform basic operations**

In [10]:
# 1) Filter rows where 'ratings_count' (proxy for Quantity) is greater than 0
# Since 'Quantity' column is not available, 'ratings_count' is used as a proxy for user engagement.
if 'ratings_count' in df.columns:
    df_filtered = df[df['ratings_count'] > 0]
    print(f'\nShape after filtering for ratings_count > 0: {df_filtered.shape}')
    print('First 5 rows of filtered data:')
    display(df_filtered.head())
else:
    df_filtered = df.copy()
    print("No 'ratings_count' column found for filtering. Keeping all rows.")

# 2) Select relevant columns for the cleaned dataset
selected_columns = ['product_id', 'title', 'product_description', 'final_price', 'ratings_count']
existing_selected_columns = [col for col in selected_columns if col in df_filtered.columns]

df_selected = df_filtered[existing_selected_columns]
print(f'\nShape after selecting columns: {df_selected.shape}')
print('First 5 rows of selected columns:')
display(df_selected.head())

Shape after filtering for ratings_count > 0: (886, 24)
First 5 rows of filtered data:

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,3995.0,INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",Unknown,Unknown,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",Unknown,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,2899.0,INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",Unknown,Unknown,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",Unknown,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,2999.0,INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",Unknown,Unknown,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",Unknown,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,1675.0,INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",Unknown,Unknown,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Unknown,Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,2899.0,INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Unknown,Unknown,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",Unknown,Unknown,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

Shape after selecting columns: (886, 5)
First 5 rows of selected columns:

,product_id,title,product_description,final_price,ratings_count
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3995.0,15
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,2899.0,67
2,17633752,Lavie,Aries Women Pink Mini Backpack,2999.0,226
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,1675.0,1052
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,2899.0,12

### **Step 5. Remove duplicates**

In [11]:
# Re-deriving df_filtered and df_selected to ensure consistency, in case of previous state issues.

# Filter rows where 'ratings_count' (proxy for Quantity) is greater than 0
if 'ratings_count' in df.columns:
    df_filtered = df[df['ratings_count'] > 0]
else:
    df_filtered = df.copy()
    print("No 'ratings_count' column found for filtering. Keeping all rows.")

# Select relevant columns for the cleaned dataset
selected_columns = ['product_id', 'title', 'product_description', 'final_price', 'ratings_count']
existing_selected_columns = [col for col in selected_columns if col in df_filtered.columns]
df_selected_fresh = df_filtered[existing_selected_columns]

print(f'Shape of df_selected before duplicate removal: {df_selected_fresh.shape}')
print('First 5 rows of df_selected before duplicate removal:')
display(df_selected_fresh.head())

initial_rows_dup = df_selected_fresh.shape[0]
df_cleaned = df_selected_fresh.drop_duplicates()
num_duplicates_removed = initial_rows_dup - df_cleaned.shape[0]

print(f'\nNumber of duplicate rows removed: {num_duplicates_removed}')
print(f'Shape after removing duplicates: {df_cleaned.shape}')
print('First 5 rows after removing duplicates:')
display(df_cleaned.head())

Shape of df_selected before duplicate removal: (886, 5)
First 5 rows of df_selected before duplicate removal:

,product_id,title,product_description,final_price,ratings_count
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3995.0,15
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,2899.0,67
2,17633752,Lavie,Aries Women Pink Mini Backpack,2999.0,226
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,1675.0,1052
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,2899.0,12

Number of duplicate rows removed: 0
Shape after removing duplicates: (886, 5)
First 5 rows after removing duplicates:

,product_id,title,product_description,final_price,ratings_count
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3995.0,15
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,2899.0,67
2,17633752,Lavie,Aries Women Pink Mini Backpack,2999.0,226
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,1675.0,1052
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,2899.0,12

### **Step 6: Create a derived column (total_amount = price * quantity)**

In [12]:
if 'final_price' in df_cleaned.columns and 'ratings_count' in df_cleaned.columns:
    df_cleaned['total_amount'] = df_cleaned['final_price'] * df_cleaned['ratings_count']
    print('\nDataFrame with new \'total_amount\' column:')
    display(df_cleaned.head())
else:
    print("Cannot create 'total_amount' column: 'final_price' or 'ratings_count' columns are missing or not numeric.")

DataFrame with new 'total_amount' column:

,product_id,title,product_description,final_price,ratings_count,total_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3995.0,15,59925.0
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,2899.0,67,194233.0
2,17633752,Lavie,Aries Women Pink Mini Backpack,2999.0,226,677774.0
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,1675.0,1052,1762100.0
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,2899.0,12,34788.0

### **Step 7: Save the cleaned dataset as a new CSV file**

In [13]:
output_file_path = 'Combined_dataset_cleaned.csv'
df_cleaned.to_csv(output_file_path, index=False)
print(f'Cleaned data saved to: {output_file_path}')

Cleaned data saved to: Combined_dataset_cleaned.csv

In [14]:
print(f'\nShape of cleaned dataset: {df_cleaned.shape}\n')
print(f'Number of rows: {df_cleaned.shape[0]}')
print(f'Number of columns: {df_cleaned.shape[1]}')

print('\nInfo of the cleaned dataset:')
df_cleaned.info()

print('\nFirst 5 rows of the cleaned dataset:')
display(df_cleaned.head())

Shape of cleaned dataset: (886, 6)

Number of rows: 886
Number of columns: 6

Info of the cleaned dataset:
<class 'pandas.core.frame.DataFrame'>
Index: 886 entries, 0 to 999
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           886 non-null    int64
 1   title                886 non-null    object
 2   product_description  886 non-null    object
 3   final_price          886 non-null    float64
 4   ratings_count        886 non-null    int64
 5   total_amount         886 non-null    float64
dtypes: float64(2), int64(2), object(2)
memory usage: 48.5+ KB

First 5 rows of the cleaned dataset:

,product_id,title,product_description,final_price,ratings_count,total_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3995.0,15,59925.0
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,2899.0,67,194233.0
2,17633752,Lavie,Aries Women Pink Mini Backpack,2999.0,226,677774.0
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,1675.0,1052,1762100.0
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,2899.0,12,34788.0

In [15]:
print('\nNull values in the cleaned dataset:')
display(df_cleaned.isnull().sum())

Null values in the cleaned dataset:

product_id             0
title                  0
product_description    0
final_price            0
ratings_count          0
total_amount           0
dtype: int64

### Brief Summary of Data Exploration and Cleaning:

*   **Initial Load**: The `Combined_dataset.csv` was successfully loaded into a Pandas DataFrame.
*   **Data Overview**: Displayed the first/last rows, checked the shape, and reviewed column names and data types.
*   **Missing Values**: Identified and handled missing values, filling object-type NaNs (e.g., `what_customers_said`, `seller_name`) with 'Unknown' and numeric NaNs (`discount`) with 0. Crucially, the `final_price` column was converted from object to numeric after cleaning currency symbols and commas.
*   **Basic Operations**: Filtered the data to include only entries where `ratings_count` (used as a proxy for quantity) is greater than 0 and selected relevant columns (`product_id`, `title`, `product_description`, `final_price`, `ratings_count`).
*   **Duplicates**: Removed duplicate rows from the dataset.
*   **Derived Column**: A new column `total_amount` was created by multiplying the cleaned `final_price` and `ratings_count`.
*   **Output**: The cleaned dataset was saved as `Combined_dataset_cleaned.csv`.